<?xml version = "1.0" encoding = "utf-8"?>
<!DOCTYPE planes_for_sale [
<!ELEMENT planes_for_sale (ad+)>
<!ELEMENT ad (year, make, model, color, description,price, seller, location)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT make (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT seller (#PCDATA)>

<!ELEMENT location (city,state)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>

<!ATTLIST seller phone CDATA #REQUIRED>
<!ATTLIST seller email CDATA #IMPLIED>
<!ENTITY c "Cessna">
<!ENTITY p "Piper">
<!ENTITY b "Beechcraft">
]>
<?xml-stylesheet type="text/css" href="2.css"?>
<planes_for_sale>
	<ad>
		
		<year> 2005 </year>
		<make> &c; </make>
		<model> A774D </model>
		<color> Black </color>
		<description> Two engine </description>
		<price> Rs. 45000 </price>
		<seller phone = "987656"> Skyway Aircraft </seller>
		<location>
			<city> Mangalore </city>
			<state> Karnataka </state>
		</location>
	</ad>

</planes_for_sale>