=== pranjal20mcaa65/xml6/3.xsd
<!-- <xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema"  elementFormDefault="qualified" attributeFormDefault="unqualified"> -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www.w3schools.com" xmlns="https://www.w3schools.com" elementFormDefault="qualified">

    <xs:element name="student">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fname" type="xs:string"></xs:element>
                            <xs:element name="mname" type="xs:string"></xs:element>
                            <xs:element name="lname" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="address">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="hno" type="xs:int"></xs:element>
                            <xs:element name="street" type="xs:string"></xs:element>
                            <xs:element name="city" type="xs:string"></xs:element>
                            <xs:element name="state" type="xs:string"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="mark" type="xs:int"></xs:element>
                <xs:element name="hobby" type="xs:string"></xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== pranjal20mcaa65/xml6/3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="3.css"?>
<student xmlns="http://www.w3.org/TR/html4"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance/" xsi:noNamespaceSchemaLocation="3.xsd">
<!-- 
<student xmlns="https://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance/" xsi:schemaLocation="https://www.w3schools.com/xml 2.xsd"> 
-->
    <name>
        <fname>jack</fname>
        <mname>Dorsey</mname>
        <lname>Jr</lname>
    </name>
    <address>
        <hno>123</hno>
        <street>hh</street>
        <city>Mangalore</city>
        <state>Karnataka</state>
    </address>
    <mark>60</mark>
    <hobby>Sleeping</hobby>
</student>
